language: generic
required: sudo
services:
  - docker

before_install:
  - docker build -t my-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true my-docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "Myfirsdockerapp"
  env: "Myfirsdockerapp-env"
  bucket_name: "elasticbeanstalk-us-east-2-748824273810"
  bucket_path: "Myfirsdockerapp"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY